import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { beforeEach, describe, expect, test, vi } from "vitest";
import { runChecker } from "../src/index.js";
import { checkerReportSchema } from "../src/report/schema.js";
import { runCommand } from "../src/utils/commands.js";

vi.mock("../src/utils/commands.js", () => ({
  runCommand: vi.fn()
}));

const mockedRunCommand = vi.mocked(runCommand);

describe("report artifacts", () => {
  beforeEach(() => {
    mockedRunCommand.mockReset();
  });

  test("writes stable report, summary, and lint log artifacts", async () => {
    const cwd = await mkdtemp(path.join(tmpdir(), "eslint-checker-report-"));
    await writeFile(
      path.join(cwd, "package.json"),
      JSON.stringify({ name: "report-fixture", version: "1.0.0" }),
      "utf8"
    );

    try {
      const report = await runChecker({
        cwd,
        options: {
          mode: "access",
          output: ".eslint-checker",
          timeout: "1",
          forIflycode: false,
          recovery: true
        }
      });

      const reportJson = JSON.parse(await readFile(path.join(cwd, ".eslint-checker/report.json"), "utf8"));
      const summary = await readFile(path.join(cwd, ".eslint-checker/summary.md"), "utf8");
      const lintLog = await readFile(path.join(cwd, ".eslint-checker/lint-log.txt"), "utf8");

      expect(reportJson).toMatchObject({
        schemaVersion: "0.2.0",
        projectInfo: { packageName: "report-fixture" },
        lintExecution: { status: "skipped", skippedReason: "access_mode" },
        eslintResolvedConfig: { status: "skipped", skippedReason: "eslint_not_connected" },
        lintResult: {
          status: "not_collected",
          problemFileCount: 0
        },
        lintEvidence: {
          topRuleExamples: [],
          topFileExamples: []
        },
        riskAssessment: { level: "medium" },
        artifacts: {
          eslintSummaryJson: ".eslint-checker/eslint-summary.json",
          eslintReportJson: null
        }
      });
      expect(report.schemaVersion).toBe("0.2.0");
      expect(summary).toContain("ESLint Checker Summary");
      expect(summary).toContain("report-fixture");
      expect(summary).toContain("eslint-summary.json");
      expect(summary).toContain("eslint-report.json: not generated by default");
      expect(summary).toContain("eslint-config.json");
      expect(lintLog).toContain("Checker started");
    } finally {
      await rm(cwd, { force: true, recursive: true });
    }
  });

  test("writes resolved ESLint config and records extended config packages", async () => {
    const cwd = await mkdtemp(path.join(tmpdir(), "eslint-checker-config-"));
    await mkdir(path.join(cwd, "src"), { recursive: true });
    await mkdir(path.join(cwd, "node_modules/.bin"), { recursive: true });
    await writeFile(path.join(cwd, "src/index.js"), "const value = 1;\n", "utf8");
    await writeFile(
      path.join(cwd, "package.json"),
      JSON.stringify({
        name: "config-fixture",
        version: "1.0.0",
        devDependencies: { eslint: "8.0.0" }
      }),
      "utf8"
    );
    await writeFile(
      path.join(cwd, ".eslintrc.json"),
      JSON.stringify({
        extends: ["eslint:recommended", "plugin:react/recommended", "standard"],
        rules: { semi: "error" }
      }),
      "utf8"
    );
    const eslintBin = path.join(cwd, "node_modules/.bin/eslint");
    await writeFile(
      eslintBin,
      [
        "#!/usr/bin/env node",
        "if (process.argv.includes('--print-config')) {",
        "  console.log(JSON.stringify({ rules: { semi: ['error', 'always'] }, parserOptions: { ecmaVersion: 2022 } }));",
        "  process.exit(0);",
        "}",
        "process.exit(1);",
        ""
      ].join("\n"),
      "utf8"
    );
    await chmod(eslintBin, 0o755);

    try {
      mockedRunCommand.mockResolvedValueOnce({
        exitCode: 0,
        stdout: JSON.stringify({ rules: { semi: ["error", "always"] }, parserOptions: { ecmaVersion: 2022 } }),
        stderr: "",
        durationMs: 10,
        timedOut: false
      });

      await runChecker({
        cwd,
        options: {
          mode: "access",
          output: ".eslint-checker",
          timeout: "5",
          forIflycode: false,
          recovery: true
        }
      });

      const reportJson = JSON.parse(await readFile(path.join(cwd, ".eslint-checker/report.json"), "utf8"));
      const resolvedConfigJson = JSON.parse(
        await readFile(path.join(cwd, ".eslint-checker/eslint-config.json"), "utf8")
      );

      expect(resolvedConfigJson).toMatchObject({
        rules: { semi: ["error", "always"] },
        parserOptions: { ecmaVersion: 2022 }
      });
      expect(reportJson.eslintResolvedConfig).toMatchObject({
        status: "success",
        targetFile: "src/index.js",
        outputPath: ".eslint-checker/eslint-config.json"
      });
      expect(reportJson.eslintConfigAnalysis.extendedConfigs).toEqual([
        "eslint:recommended",
        "plugin:react/recommended",
        "standard"
      ]);
      expect(reportJson.eslintConfigAnalysis.extendedPackages).toEqual([
        "eslint",
        "eslint-plugin-react",
        "eslint-config-standard"
      ]);
      expect(reportJson.artifacts.eslintConfigJson).toBe(".eslint-checker/eslint-config.json");
    } finally {
      await rm(cwd, { force: true, recursive: true });
    }
  });

  test("parses summary artifact and omits raw ESLint report by default", async () => {
    const cwd = await createFullModeFixture("eslint-checker-summary-default-");
    try {
      mockFullModeCommands(cwd, { rawEslintReport: false });

      await runChecker({
        cwd,
        options: {
          mode: "full",
          output: ".eslint-checker",
          timeout: "5",
          forIflycode: false,
          recovery: true
        }
      });

      const reportJson = JSON.parse(await readFile(path.join(cwd, ".eslint-checker/report.json"), "utf8"));
      const summary = await readFile(path.join(cwd, ".eslint-checker/summary.md"), "utf8");

      expect(reportJson.lintResult).toMatchObject({
        status: "success",
        errorCount: 1,
        warningCount: 1,
        fileCount: 1,
        problemFileCount: 1
      });
      expect(reportJson.lintEvidence.topRuleExamples).toEqual([
        {
          ruleId: "no-alert",
          severity: "error",
          filePath: "src/index.js",
          line: 1,
          column: 1,
          message: "Unexpected alert."
        }
      ]);
      expect(reportJson.artifacts).toMatchObject({
        eslintSummaryJson: ".eslint-checker/eslint-summary.json",
        eslintReportJson: null
      });
      expect(summary).toContain("- eslint-summary.json: .eslint-checker/eslint-summary.json");
      expect(summary).toContain("- eslint-report.json: not generated by default");
      expect(mockedRunCommand).toHaveBeenCalledTimes(2);
    } finally {
      await rm(cwd, { force: true, recursive: true });
    }
  });

  test("report schema requires lint problem file count and structured lint evidence", async () => {
    const cwd = await createFullModeFixture("eslint-checker-schema-");
    try {
      mockFullModeCommands(cwd, { rawEslintReport: false });

      const report = await runChecker({
        cwd,
        options: {
          mode: "full",
          output: ".eslint-checker",
          timeout: "5",
          forIflycode: false,
          recovery: true
        }
      });

      expect(checkerReportSchema.safeParse(report).success).toBe(true);
      expect(checkerReportSchema.safeParse({ ...report, schemaVersion: "0.1.0" }).success).toBe(false);
      expect(checkerReportSchema.safeParse({ ...report, lintEvidence: undefined }).success).toBe(false);
      expect(
        checkerReportSchema.safeParse({
          ...report,
          lintResult: { ...report.lintResult, problemFileCount: undefined }
        }).success
      ).toBe(false);
      expect(
        checkerReportSchema.safeParse({
          ...report,
          lintEvidence: { topRuleExamples: [{ ruleId: "no-alert" }], topFileExamples: [] }
        }).success
      ).toBe(false);
    } finally {
      await rm(cwd, { force: true, recursive: true });
    }
  });

  test("records raw ESLint report artifact path when raw debug mode is enabled", async () => {
    const cwd = await createFullModeFixture("eslint-checker-summary-raw-");
    try {
      mockFullModeCommands(cwd, { rawEslintReport: true });

      await runChecker({
        cwd,
        options: {
          mode: "full",
          output: ".eslint-checker",
          timeout: "5",
          forIflycode: false,
          recovery: true,
          rawEslintReport: true
        }
      });

      const reportJson = JSON.parse(await readFile(path.join(cwd, ".eslint-checker/report.json"), "utf8"));
      const summary = await readFile(path.join(cwd, ".eslint-checker/summary.md"), "utf8");

      expect(reportJson.artifacts).toMatchObject({
        eslintSummaryJson: ".eslint-checker/eslint-summary.json",
        eslintReportJson: ".eslint-checker/eslint-report.json"
      });
      expect(summary).toContain("- eslint-report.json: .eslint-checker/eslint-report.json");
      expect(mockedRunCommand).toHaveBeenCalledTimes(3);
    } finally {
      await rm(cwd, { force: true, recursive: true });
    }
  });

  test("emits console process logs when enabled", async () => {
    const cwd = await mkdtemp(path.join(tmpdir(), "eslint-checker-console-"));
    await writeFile(
      path.join(cwd, "package.json"),
      JSON.stringify({ name: "console-fixture", version: "1.0.0" }),
      "utf8"
    );
    const consoleLog = vi.spyOn(console, "log").mockImplementation(() => undefined);

    try {
      await runChecker({
        cwd,
        options: {
          mode: "access",
          output: ".eslint-checker",
          timeout: "1",
          forIflycode: false,
          recovery: true,
          console: true
        }
      });

      const output = consoleLog.mock.calls.map((call) => call.join(" ")).join("\n");
      expect(output).toContain("[eslint-checker] [1/7] Initializing check");
      expect(output).toContain("[eslint-checker] [2/7] Discovering project and static ESLint context");
      expect(output).toContain("[eslint-checker] [3/7] Collecting resolved ESLint config");
      expect(output).toContain("[eslint-checker] [4/7] Collecting ESLint results");
      expect(output).toContain("[eslint-checker] [5/7] Parsing ESLint output");
      expect(output).toContain("[eslint-checker] [6/7] Assessing risk and composing report");
      expect(output).toContain("[eslint-checker] [7/7] Writing report artifacts");
      expect(output).toContain("[eslint-checker] Done. Report: .eslint-checker/report.json");
    } finally {
      consoleLog.mockRestore();
      await rm(cwd, { force: true, recursive: true });
    }
  });
});

async function createFullModeFixture(prefix: string): Promise<string> {
  const cwd = await mkdtemp(path.join(tmpdir(), prefix));
  await mkdir(path.join(cwd, "src"), { recursive: true });
  await writeFile(path.join(cwd, "src/index.js"), "alert('x');\n", "utf8");
  await writeFile(
    path.join(cwd, "package.json"),
    JSON.stringify({
      name: "summary-fixture",
      version: "1.0.0",
      scripts: { lint: "eslint ." },
      devDependencies: { eslint: "8.0.0" }
    }),
    "utf8"
  );
  await writeFile(path.join(cwd, ".eslintrc.json"), JSON.stringify({ rules: { "no-alert": "error" } }), "utf8");
  return cwd;
}

function mockFullModeCommands(cwd: string, { rawEslintReport }: { rawEslintReport: boolean }): void {
  mockedRunCommand.mockImplementation(async ({ args }) => {
    if (args.includes("--print-config")) {
      return {
        exitCode: 0,
        stdout: JSON.stringify({ rules: { "no-alert": ["error"] } }),
        stderr: "",
        durationMs: 10,
        timedOut: false
      };
    }

    if (args.some((arg) => arg.endsWith("eslint-summary.json"))) {
      await mkdir(path.join(cwd, ".eslint-checker"), { recursive: true });
      await writeFile(
        path.join(cwd, ".eslint-checker/eslint-summary.json"),
        JSON.stringify({
          schemaVersion: "0.1.0",
          generatedAt: "2026-06-04T00:00:00.000Z",
          lintResult: {
            status: "success",
            errorCount: 1,
            warningCount: 1,
            fixableErrorCount: 0,
            fixableWarningCount: 1,
            fileCount: 1,
            problemFileCount: 1
          },
          ruleSummary: [
            { ruleId: "no-alert", severity: "error", count: 1, fixableCount: 0 },
            { ruleId: "no-console", severity: "warning", count: 1, fixableCount: 1 }
          ],
          fileSummary: [{ filePath: "src/index.js", errorCount: 1, warningCount: 1, disableCount: 0 }],
          evidence: {
            topRuleExamples: [
              {
                ruleId: "no-alert",
                severity: "error",
                filePath: "src/index.js",
                line: 1,
                column: 1,
                message: "Unexpected alert."
              }
            ],
            topFileExamples: [
              {
                filePath: "src/index.js",
                errorCount: 1,
                warningCount: 1,
                examples: [
                  {
                    ruleId: "no-alert",
                    severity: "error",
                    filePath: "src/index.js",
                    line: 1,
                    column: 1,
                    message: "Unexpected alert."
                  }
                ]
              }
            ]
          },
          limits: {
            maxRules: 20,
            maxFiles: 20,
            maxExamplesPerRule: 3,
            maxExamplesPerFile: 3,
            maxMessageLength: 200
          }
        }),
        "utf8"
      );
      return {
        exitCode: 1,
        stdout: "",
        stderr: "",
        durationMs: 20,
        timedOut: false
      };
    }

    if (rawEslintReport && args.some((arg) => arg.endsWith("eslint-report.json"))) {
      return {
        exitCode: 1,
        stdout: "",
        stderr: "",
        durationMs: 15,
        timedOut: false
      };
    }

    return {
      exitCode: 2,
      stdout: "",
      stderr: "unexpected command",
      durationMs: 1,
      timedOut: false
    };
  });
}
